/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // 1. 首页概览
    {
      type: 'doc',
      id: 'intro',
      label: '学习概览',
      className: 'sidebar-icon-dashboard',
    },

    // 2. 数组 (Array)
    {
      type: 'category',
      label: '数组',
      className: 'sidebar-icon-array',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          {
          type: 'autogenerated',
          dirName: 'array', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },

    // 3. 线性表 (Linear List)
    {
      type: 'category',
       // 这里假设你原来的 demo.mdx 是线性表总览
      label: '线性表',
      className: 'sidebar-icon-linkedlist',
      link: { type: 'generated-index' },
      items: [
          {
          type: 'autogenerated',
          dirName: 'list', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],// 借用链表图标
    },

    // 4. 栈 (Stack)
    {
      type: 'category',
      label: '栈',
      className: 'sidebar-icon-stack-structure',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          {
          type: 'autogenerated',
          dirName: 'stack', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },

    // 5. 队列 (Queue)
    {
      type: 'category',
      label: '队列',
      className: 'sidebar-icon-queue',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          {
          type: 'autogenerated',
          dirName: 'queue', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },

    // 6. 字符串 (String)
    {
      type: 'category',
      label: '字符串',
      className: 'sidebar-icon-string',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          'string/intro',
          'string/operate',
          'string/seq',
          'string/chain',
          'string/achieve',
          'string/heap',
          'string/code',
          'string/match',
          'string/next',
          'string/nextval',
      ],
    },

    // 7. 树与二叉树 (Category - 依然保持文件夹结构，但也是一级并列)
    {
      type: 'category',
      label: '树与二叉树',
      className: 'sidebar-icon-tree',
      link: { type: 'generated-index' },
      collapsed: true, // 默认收起，保持侧边栏整洁
      items: [
        {
          type: 'autogenerated',
          dirName: 'tree', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },

    // 8. 图论 (Category)
    {
      type: 'category',
      label: '图论算法',
      className: 'sidebar-icon-network',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          {
          type: 'autogenerated',
          dirName: 'graph', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },

    // 9. 哈希表
    {
      type: 'category',
      label: '哈希表',
      className: 'sidebar-icon-hash',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          {
          type: 'autogenerated',
          dirName: 'hash', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },

    // 10. 贪心算法
    {
      type: 'category',
      label: '贪心算法',
      className: 'sidebar-icon-greedy',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          {
          type: 'autogenerated',
          dirName: 'greedy', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },

    // 11. 回溯算法
    {
      type: 'category',
      label: '回溯算法',
      className: 'sidebar-icon-backtrack',
      link: { type: 'generated-index' },
      collapsed: true,
      items: ['backtrack/intro'], // 确保 docs/backtrack/intro.md 存在
    },

    // 9. 排序 (Sort)
    {
      type: 'category',
      label: '十大排序',
      className: 'sidebar-icon-sort',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{
          type: 'autogenerated',
          dirName: 'sort', // 自动扫描 docs/string 文件夹下的所有文件
        },],
    },

    // 10. 查找 (Search)
    {
      type: 'category',

      label: '查找算法',
      className: 'sidebar-icon-search',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [
          {
          type: 'autogenerated',
          dirName: 'search', // 自动扫描 docs/string 文件夹下的所有文件
        },
      ],
    },
  ],
};

module.exports = sidebars;